const PASSPHRASE_ADJECTIVES = [
  "amber", "ancient", "alpine", "arctic", "ashen", "auburn", "autumn", "azure",
  "bold", "bright", "brisk", "bronze", "calm", "canyon", "cedar", "clear",
  "cobalt", "cool", "copper", "coral", "cosmic", "crisp", "crimson", "current",
  "daring", "dawn", "deep", "delta", "dry", "dusky", "eager", "early",
  "earthen", "eastern", "ember", "endless", "even", "fabled", "faint", "fair",
  "far", "feral", "fern", "fiery", "fine", "first", "flint", "flinty",
  "floral", "foggy", "forest", "frost", "gentle", "glacial", "glowing", "golden",
  "grand", "gray", "green", "harbor", "hazy", "hidden", "hollow", "humble",
  "indigo", "inner", "iron", "ivory", "jade", "jasper", "jolly", "keen",
  "kind", "kindled", "leafy", "lilac", "lively", "lunar", "maple", "marble",
  "meadow", "mellow", "misty", "modern", "mossy", "narrow", "navy", "nickel",
  "noble", "northern", "obsidian", "olive", "onyx", "opal", "open", "orchid",
  "outer", "pale", "pearl", "pebbled", "pine", "plain", "polar", "primal",
  "prime", "proud", "pure", "quartz", "quiet", "radiant", "rapid", "raw",
  "red", "rich", "rising", "river", "rooted", "royal", "rustic", "sable",
  "saffron", "salty", "sandy", "scarlet", "shady", "shadow", "sierra", "silent",
  "silken", "silver", "simple", "slate", "sleek", "small", "smooth", "soft",
  "solar", "solid", "southern", "sparse", "spruce", "starlit", "steel", "still",
  "stone", "stormy", "stout", "subtle", "sunlit", "sunny", "swift", "teal",
  "temperate", "terra", "tidal", "timber", "topaz", "true", "umber", "urban",
  "vast", "veiled", "velvet", "verdant", "violet", "vital", "vivid", "waking",
  "warm", "western", "wild", "willow", "windy", "winter", "wooden", "woven",
  "young", "zen", "zephyr", "zesty",
] as const;

const PASSPHRASE_NOUNS = [
  "acorn", "anchor", "angle", "anvil", "apple", "arbor", "arch", "atlas",
  "aura", "bamboo", "basin", "bay", "beacon", "birch", "blossom", "bluff",
  "boulder", "branch", "breeze", "brook", "cactus", "candle", "canyon", "chain",
  "cinder", "cipher", "citadel", "cliff", "cloud", "clover", "cluster", "comet",
  "copper", "coral", "cove", "crater", "creek", "crest", "dagger", "delta",
  "dew", "domain", "drift", "dune", "echo", "elm", "ember", "engine",
  "estuary", "falcon", "field", "finch", "fjord", "flame", "flint", "ford",
  "forest", "forge", "fusion", "galaxy", "garden", "geyser", "glacier", "glade",
  "granite", "grove", "gulf", "harbor", "haven", "heath", "helm", "heron",
  "hive", "horizon", "inlet", "iris", "island", "islet", "ivory", "jasper",
  "jungle", "keel", "kelp", "kernel", "knoll", "lagoon", "lantern", "larch",
  "lark", "ledger", "ledge", "lichen", "lighthouse", "lotus", "maple", "marina",
  "marsh", "matrix", "meadow", "mesa", "mirror", "mist", "module", "monolith",
  "moon", "morning", "moss", "nebula", "nectar", "needle", "nickel", "oak",
  "oasis", "obsidian", "olive", "onyx", "opal", "orbit", "orchard", "orchid",
  "osprey", "otter", "oxbow", "packet", "pass", "pebble", "petal", "pine",
  "pinnacle", "pixel", "planet", "plaza", "plume", "pond", "poplar", "port",
  "prairie", "prism", "quarry", "quartz", "quill", "radius", "rapids", "raven",
  "reed", "reef", "refuge", "ridge", "ripple", "river", "runnel", "sage",
  "sakura", "salmon", "sand", "sapphire", "savanna", "schema", "shadow", "shield",
  "shore", "signal", "sky", "socket", "solstice", "spear", "spire", "spring",
  "spruce", "star", "stone", "storm", "strait", "stream", "summit", "sun",
  "sunset", "surf", "system", "terrace", "thicket", "thread", "thunder", "tide",
  "timber", "torch", "trail", "trench", "trout", "tulip", "tundra", "universe",
  "valley", "vault", "vector", "vertex", "violet", "vista", "voyage", "walnut",
  "waterfall", "wave", "weir", "well", "wharf", "wheat", "wick", "willow",
  "wind", "woodland", "yarrow", "zenith", "zephyr",
  "abacus", "agate", "alder", "ambergris", "aspen", "aster", "badger", "barley",
  "basalt", "beech", "bell", "beryl", "bison", "bramble", "bronze", "cabin",
  "cairn", "camel", "cedar", "chisel", "cicada", "citrine", "cloak", "cobalt",
  "crane", "crystal", "cypress", "dahlia", "daisy", "dock", "dolphin", "eagle",
  "eddy", "elk", "fawn", "fern", "fig", "fir", "fox", "garnet",
  "gate", "ginger", "gold", "goose", "gull", "hazel", "holly", "honey",
  "horse", "hyacinth", "ibis", "ink", "ivy", "juniper", "kite", "lake",
  "lamp", "laurel", "linen", "lynx", "magnet", "magnetite", "mango", "mantle",
  "marlin", "mint", "mule", "mulberry",   "nimbus", "notch",
  "orange", "osier", "owl", "ox", "palm", "panther", "paper",
  "peach", "pear", "pepper", "perch", "phoenix", "plover", "poppy", "porch",
  "puma", "rain", "ram", "robin", "rowan", "ruby", "rye", "sail",
  "seal", "seed", "sequoia", "sheep", "shell", "silk", "silo", "sparrow",
  "spice", "spine", "stallion", "swan", "sycamore", "talon", "temple", "thorn",
  "thrush", "tiger", "topsoil", "tower", "truffle", "turtle", "vine",
  "vixen", "wren", "yarn", "yew", "quartzite", "sandstone", "limestone", "redwood", "dogwood",
] as const;

export const PASSPHRASE_WORDS: readonly string[] = [
  ...new Set([...PASSPHRASE_ADJECTIVES, ...PASSPHRASE_NOUNS]),
].sort((left, right) => left.localeCompare(right));
